# Generated by Django 6.1 on 2026-08-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='city',
            new_name='City',
        ),
    ]
